modules-search: [ local ]

instances:
  - module: shellprocess
    id: kernel
    config: shellprocess@kernel.conf
  - module: shellprocess
    id: done
    config: shellprocess@done.conf

sequence:
  - show:
      - welcome
      - locale
      - keyboard
      - partition
      - users
      - summary
  - exec:
      - partition
      - mount
      - unpackfs
      - shellprocess@kernel
      - machineid
      - locale
      - keyboard
      - localecfg
      - fstab
      - users
      - displaymanager
      - grubcfg
      - bootloader
      - shellprocess@done
  - show:
      - finished

branding: kutu
dont-chroot: false
