defaultFileSystemType: ext4
initialPartitioningChoice: none
userSwapChoices: [ none, small, suspend, file ]
initialSwapChoice: suspend
luksGeneration: luks2
enableLuksAutomatedPartitioning: true
requiredPartitionTableType: gpt
