dontChroot: true
script:
  - "cp -a /run/archiso/bootmnt/kutu/boot/x86_64/vmlinuz-linux ${ROOT}/boot/"
  - command: "chroot ${ROOT} mkinitcpio -P"
    timeout: 900
  - "test -f ${ROOT}/boot/vmlinuz-linux -a -f ${ROOT}/boot/initramfs-linux.img"
