dontChroot: true
script:
  - "-/usr/bin/sed -i 's|Server = file://[^ ]*|Server = https://kutu-so.github.io/os/repo/x86_64|' ${ROOT}/etc/pacman.conf"
  - "-/usr/bin/rm -f ${ROOT}/etc/lightdm/lightdm.conf.d/20-kutu-live.conf"
  - "-/usr/bin/rm -f ${ROOT}/etc/systemd/system/getty@tty1.service.d/autologin.conf"
  - "-/usr/bin/rm -f ${ROOT}/etc/systemd/system/serial-getty@ttyS0.service.d/autologin.conf"
  - "-/usr/bin/rm -f ${ROOT}/etc/sudoers.d/g_wheel"
  - "-/usr/sbin/chroot ${ROOT} /usr/bin/userdel -r kutu"
  - "-/usr/bin/systemctl --root=${ROOT} enable kutu-firstboot.service"
