dontChroot: true
script:
  - "cp -a /run/archiso/bootmnt/kutu/boot/x86_64/vmlinuz-linux ${ROOT}/boot/"
  - "rm -f ${ROOT}/etc/mkinitcpio.conf.d/archiso.conf"
  - "echo 'MODULES=()' > ${ROOT}/etc/mkinitcpio.conf"
  - "echo 'BINARIES=()' >> ${ROOT}/etc/mkinitcpio.conf"
  - "echo 'FILES=()' >> ${ROOT}/etc/mkinitcpio.conf"
  - "echo 'HOOKS=(base udev autodetect modconf kms keyboard fsck)' >> ${ROOT}/etc/mkinitcpio.conf"
  - "echo \"ALL_kver='/boot/vmlinuz-linux'\" > ${ROOT}/etc/mkinitcpio.d/linux.preset"
  - "echo \"PRESETS=('default' 'fallback')\" >> ${ROOT}/etc/mkinitcpio.d/linux.preset"
  - "echo \"default_image='/boot/initramfs-linux.img'\" >> ${ROOT}/etc/mkinitcpio.d/linux.preset"
  - "echo \"fallback_image='/boot/initramfs-linux-fallback.img'\" >> ${ROOT}/etc/mkinitcpio.d/linux.preset"
  - "echo \"fallback_options='-S autodetect'\" >> ${ROOT}/etc/mkinitcpio.d/linux.preset"
  - command: "chroot ${ROOT} mkinitcpio -P"
    timeout: 900
  - "test -f ${ROOT}/boot/vmlinuz-linux -a -f ${ROOT}/boot/initramfs-linux.img"
