dontChroot: true
script:
  - "cp -a /run/archiso/bootmnt/kutu/boot/x86_64/vmlinuz-linux ${ROOT}/boot/"
  - "rm -f ${ROOT}/etc/mkinitcpio.conf.d/archiso.conf"
  - "install -Dm644 /etc/calamares/presets/linux.preset ${ROOT}/etc/mkinitcpio.d/linux.preset"
  - "test -f ${ROOT}/boot/vmlinuz-linux"
