defaultGroups: [ wheel, users ]
autologinGroup: autologin
doAutologin: false
setRootPassword: false
sudoersGroup: wheel
user:
  forbidden_names: [ kutu ]
passwordRequirements:
  nonEmpty: true
  minLength: 8
