title    kutu OS (LTS kernel)
sort-key 02
linux    /%INSTALL_DIR%/boot/%ARCH%/vmlinuz-linux-lts
initrd   /%INSTALL_DIR%/boot/%ARCH%/initramfs-linux-lts.img
options  archisobasedir=%INSTALL_DIR% archisosearchuuid=%ARCHISO_UUID% zswap.enabled=1 zswap.compressor=zstd zswap.max_pool_percent=35 zswap.shrinker_enabled=1 psi=1 transparent_hugepage=madvise console=tty0 console=ttyS0,115200
