#!/bin/bash
# kutu OS - Post-Install Kernel Optimization Script
# Applies full kernel optimizations after installation
# Detects hardware and applies appropriate parameters to GRUB
#
# Usage:
#   sudo install-kernel-optimizations.sh          # Interactive mode (prompts for reboot)
#   sudo install-kernel-optimizations.sh --non-interactive  # Non-interactive (no reboot prompt)

set -e

# Parse arguments
NON_INTERACTIVE=false
if [[ "$1" == "--non-interactive" ]]; then
    NON_INTERACTIVE=true
fi

# Color output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

log() {
    echo -e "${GREEN}[KERNEL]${NC} $*"
}

warn() {
    echo -e "${YELLOW}[WARN]${NC} $*"
}

error() {
    echo -e "${RED}[ERROR]${NC} $*"
    exit 1
}

# Check if running as root
if [[ $EUID -ne 0 ]]; then
    error "This script must be run as root. Use: sudo $0"
fi

log "Detecting hardware..."

# Detect CPU count
CPU_COUNT=$(nproc)
log "Detected $CPU_COUNT CPUs"

# Calculate isolation range (isolate all except CPU 0)
if [ $CPU_COUNT -le 2 ]; then
    warn "Only $CPU_COUNT CPUs detected. CPU isolation not recommended."
    ISOLATE_CPUS=""
elif [ $CPU_COUNT -le 16 ]; then
    ISOLATE_CPUS="1-$((CPU_COUNT - 1))"
else
    # For systems with >16 cores, isolate all except first 2
    ISOLATE_CPUS="2-$((CPU_COUNT - 1))"
fi

# Detect GPU
GPU_VENDOR="unknown"
HW_PARAMS=""

if lspci | grep -qi "AMD.*VGA"; then
    GPU_VENDOR="amd"
    log "Detected AMD GPU"
    HW_PARAMS="amdgpu.gttsize=131072 ttm.pages_limit=33554432 amd_iommu=on iommu=pt "
    HW_PARAMS+="amdgpu.sched_policy=0 amdgpu.cwsr_enable=1 amdgpu.mcbp=-1 "
    HW_PARAMS+="amdgpu.lockup_timeout=10000,60000,10000,10000 amdgpu.dpm=1 amdgpu.ppfeaturemask=0xffffffff "
    HW_PARAMS+="amd_pstate=active initcall_blacklist=acpi_cpufreq_init processor.max_cstate=2"

elif lspci | grep -qi "Intel.*VGA"; then
    GPU_VENDOR="intel"
    log "Detected Intel GPU"
    HW_PARAMS="intel_iommu=on iommu=pt i915.enable_guc=3 i915.enable_rc6=1 i915.enable_fbc=1 "
    HW_PARAMS+="intel_pstate=active intel_idle.max_cstate=2"

elif lspci | grep -qi "NVIDIA"; then
    GPU_VENDOR="nvidia"
    log "Detected NVIDIA GPU"
    HW_PARAMS="nvidia-drm.modeset=1 nvidia.NVreg_PreserveVideoMemoryAllocations=1"
fi

# Build kernel command line
CMDLINE="quiet splash loglevel=3 "
CMDLINE+="mitigations=off "
CMDLINE+="transparent_hugepage=madvise hugepagesz=2M default_hugepagesz=2M hugepages=2048 "
CMDLINE+="numa=fake=4 numa_balancing=enable "
CMDLINE+="nvme_core.default_ps_max_latency_us=0 "
CMDLINE+="nowatchdog nmi_watchdog=0 "
CMDLINE+="audit=0 "
CMDLINE+="pcie_aspm=performance "
CMDLINE+="pid_max=4194304 "

# Add CPU isolation if applicable
if [ -n "$ISOLATE_CPUS" ]; then
    CMDLINE+="nohz_full=$ISOLATE_CPUS rcu_nocbs=$ISOLATE_CPUS "
    CMDLINE+="isolcpus=managed_irq,domain,$ISOLATE_CPUS irqaffinity=0 "
    log "CPU isolation configured: $ISOLATE_CPUS"
else
    warn "CPU isolation skipped (insufficient cores)"
fi

# Add preemption and IRQ threading
CMDLINE+="threadirqs preempt=full "

# Add hardware-specific parameters
if [ -n "$HW_PARAMS" ]; then
    CMDLINE+="$HW_PARAMS"
    log "Added $GPU_VENDOR-specific parameters"
fi

# Backup existing GRUB config
if [ -f /etc/default/grub ]; then
    log "Backing up /etc/default/grub..."
    cp /etc/default/grub /etc/default/grub.backup.$(date +%Y%m%d_%H%M%S)
fi

# Update GRUB configuration
log "Updating GRUB configuration..."

# Read current GRUB_CMDLINE_LINUX_DEFAULT
if [ -f /etc/default/grub ]; then
    # Remove old GRUB_CMDLINE_LINUX_DEFAULT line and add new one
    sed -i '/^GRUB_CMDLINE_LINUX_DEFAULT=/d' /etc/default/grub
fi

# Append new configuration
cat >> /etc/default/grub << EOF

# kutu OS Kernel Optimizations
# Generated by install-kernel-optimizations.sh on $(date)
# Hardware: $CPU_COUNT CPUs, $GPU_VENDOR GPU
GRUB_CMDLINE_LINUX_DEFAULT="$CMDLINE"
EOF

log "GRUB configuration updated"

# Regenerate GRUB config
log "Regenerating GRUB configuration..."
if [ -d /boot/grub ]; then
    grub-mkconfig -o /boot/grub/grub.cfg
    log "GRUB configuration regenerated"
else
    warn "/boot/grub not found. Regenerate manually with: grub-mkconfig -o /boot/grub/grub.cfg"
fi

# Summary
echo ""
echo -e "${BLUE}================================${NC}"
echo -e "${BLUE}Kernel Optimization Summary${NC}"
echo -e "${BLUE}================================${NC}"
echo -e "CPU Count:      ${GREEN}$CPU_COUNT${NC}"
if [ -n "$ISOLATE_CPUS" ]; then
    echo -e "CPU Isolation:  ${GREEN}$ISOLATE_CPUS${NC}"
else
    echo -e "CPU Isolation:  ${YELLOW}Disabled${NC}"
fi
echo -e "GPU Vendor:     ${GREEN}$GPU_VENDOR${NC}"
echo -e "NUMA Emulation: ${GREEN}Enabled (4 nodes)${NC}"
echo -e "Huge Pages:     ${GREEN}2048 x 2MB${NC}"
echo -e "Preemption:     ${GREEN}Full (sub-100μs latency)${NC}"
echo ""
echo -e "${GREEN}✓${NC} Kernel optimizations applied successfully!"
echo -e "${YELLOW}⚠${NC} Reboot required for changes to take effect"
echo ""
echo "After reboot, validate with:"
echo "  sudo validate-kernel.sh"
echo ""
echo "Monitor performance with:"
echo "  monitor-kernel.sh"
echo ""

if [[ "$NON_INTERACTIVE" == "false" ]]; then
    read -p "Reboot now? (y/N) " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        log "Rebooting..."
        reboot
    fi
else
    log "Non-interactive mode: Skipping reboot prompt"
    log "Reboot required for kernel optimizations to take effect"
fi
